.Dd August 10, 2024
.Dt sjauth 1
.Os "YK Pao School Utilities"
.
.Sh NAME
.Nm sjauth
.Nd authenticate to YK Pao School's STUWIRELESS captive portal
.
.Sh SYNOPSIS
.Nm
.Ar username
.Ar passvar
.
.Sh DESCRIPTION
.Pp
The
.Nm
script makes a single HTTP request to YK Pao School's STUWIRELESS captive portal
to authenticate users.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Ar username
Your YK Pao School username (such as s65535)
.It Ar passvar
The name of an environment variable containing your password
.El
.Sh AUTHORS
.Pp
.An Runxi Yu Aq Mt me@runxiyu.org
.
.Sh BUGS
.Pp
Send mail to
.Aq Mt ~runxiyu/public-inbox@list.sr.ht
